### PR TITLE
add yarn start command

### PR DESCRIPTION
**Pull request by TheRealSyler**
combines `rails s` with `guard -i -g livereload` into `yarn start`

### CODE REVIEW

**Comment by fwolfst** [comment]
Afaik at the moment we do not use yarn at all (https://github.com/ecovillage/cabler/commit/c1f38256350dfce601e8fd76e82efbbc95d3e134). If we would, we could just use the rails `bin/webpack-dev-server`, I believe.
Or is it exactly the other way around? You want yarn to start the live-reload?!

I will not merge this PR now, but want to understand what it exactly does - best we do this together in person, at a table.

**Comment by fwolfst** [comment]
Okay, I understood.
Please add a sentence or section to the README. Maybe it makes sense to have `start-dev` and `start` as command? Because the livereload stuff will not be present in production environments. Or are yarn commands generally only used during dev?

**Comment by TheRealSyler** [comment]
sure, `start-dev` or just `dev` makes more sense.

**Comment by fwolfst** [comment]
imho branch can be closed?

**Pull request merged**
